//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using MenuManager;
    
    public partial class Employee
    {
        public int ID { get; set; }

        [Required,
         Display(Name="First Name"),
         StringLength(20, ErrorMessage = Helpers.TOO_LONG)]
        public string FName { get; set; }

        [Required,
         Display(Name = "Last Name"),
         StringLength(20, ErrorMessage = Helpers.TOO_LONG)]
        public string LName { get; set; }

        public string Name
        {
            get { return FName + " " + LName; }
        }

        [Required,
         StringLength(20, ErrorMessage = Helpers.TOO_LONG)]
        public string Position { get; set; }
        
        [Required]
        public decimal Wage { get; set; }

        [Required,
         StringLength(15, ErrorMessage = Helpers.TOO_LONG)]
        public string Phone { get; set; }

        [Required,
         Display(Name="Store ID")]
        public int Store_ID { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
