//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        [Required]
        public int ID { get; set; }

        [Required,
         StringLength(20, ErrorMessage = Helpers.TOO_LONG)]
        public string Name { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required,
         Display(Name = "Menu ID")]
        public int Menu_ID { get; set; }

        public Nullable<int> Calories { get; set; }

        [Display(Name = "Vegetarian")]
        public Nullable<bool> Is_Vegetarian { get; set; }

        public string IsVegetarianYesNo
        {
            get
            {
                if (Is_Vegetarian == null)
                    return string.Empty;
                else if ((bool)Is_Vegetarian)
                    return "Yes";
                else
                    return "No";
            }
        }

        [Display(Name = "Vegan")]
        public Nullable<bool> Is_Vegan { get; set; }

        public string IsVeganYesNo
        {
            get
            {
                if (Is_Vegan == null)
                    return string.Empty;
                else if ((bool)Is_Vegan)
                    return "Yes";
                else
                    return "No";
            }
        }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
