//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }

        [Required]
        public int ID { get; set; }

        [Required,
         StringLength(20, ErrorMessage = Helpers.TOO_LONG)]
        public string Name { get; set; }

        [Required,
         Display(Name = "Store ID")]
        public int Store_ID { get; set; }

        public virtual Store Store { get; set; }

        [Display(Name = "Menu Items")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }

        public ICollection<Ingredient> Ingredients
        {
            get
            {
                List<Ingredient> list = new List<Ingredient>();
                foreach (MenuItem mi in MenuItems)
                {
                    foreach (Ingredient i in mi.Ingredients)
                    {
                        if (!list.Contains(i))
                            list.Add(i);
                    }
                }
                return list;
            }
        }

        public string NameAndStore
        {
            get { return Name + ", " + Store.Name; }
        }

        public string StoreAndName
        {
            get { return Store.Name + ", " + Name; }
        }
    }
}
