//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Store
    {
        public Store()
        {
            this.Employees = new HashSet<Employee>();
            this.Ingredients = new HashSet<Ingredient>();
            this.Menus = new HashSet<Menu>();
        }

        [Required]
        public int ID { get; set; }

        [Required,
         StringLength(25, ErrorMessage = Helpers.TOO_LONG)]
        public string Name { get; set; }

        [Required,
         StringLength(15, ErrorMessage = Helpers.TOO_LONG)]
        public string Phone { get; set; }

        [Required,
         StringLength(100, ErrorMessage = Helpers.TOO_LONG)]
        public string Address { get; set; }
        
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }

        [Display(Name="Menu Items")]
        public ICollection<MenuItem> MenuItems
        {
            get
            {
                List<MenuItem> list = new List<MenuItem>();
                foreach (Menu m in Menus)
                {
                    foreach (MenuItem mi in m.MenuItems)
                    {
                        list.Add(mi);
                    }
                }
                return list;
            }
        }
    }
}
